services:
 backend:
   build: .
   container_name: backend
   command: python manage.py runserver 0.0.0.0:8000
   ports:
     - "8000:8000"
   volumes:
     - ./core:/app
   environment:
     - SECRET_KEY=test
     - DEBUG=True